---
services:
  fruits-db:
    image: postgres:15
    restart: unless-stopped
    container_name: fruits-db
    ports:
      - 8434:5432
    environment:
      POSTGRES_USER: fruits
      POSTGRES_PASSWORD: fruits
      POSTGRES_DB: fruits
    volumes:
      - ./src/main/resources/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    labels:
      # https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#features.docker-compose.custom-images
      org.springframework.boot.service-connection: postgres
