---
services:
  sonarqube-change-password:
    image: ubuntu:22.04
    container_name: sonarqube-change-password
    depends_on:
      sonarqube:
        condition: service_healthy
    command: >
      sh -c "apt update
      && apt install -y curl
      && curl -u admin:admin -X POST 'http://sonarqube:9000/api/users/change_password?login=admin&previousPassword=admin&password=sonarqube'"

  sonarqube:
    image: sonarqube:community
    hostname: sonarqube
    container_name: sonarqube
    depends_on:
      - sonarqube-db
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://sonarqube-db:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
    ports:
      - 9000:9000
    healthcheck:
      test: curl -sS http://localhost:9000/api/system/status | grep -e '"status":"UP"' > /dev/null
      interval: 10s
      timeout: 30s
      retries: 5
      start_period: 30s

  sonarqube-db:
    image: postgres:15
    hostname: sonarqube-db
    container_name: sonarqube-db
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      POSTGRES_DB: sonar
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data

volumes:
  sonarqube_data:
  sonarqube_extensions:
  postgresql:
  postgresql_data:
