namespace:
  name: ewetchy-amrit

replicaCount: 1

image:
  repository: docker-repo.bodc.me/ewetchy/amrit/api
  pullPolicy: IfNotPresent
  tag: "1.0.0"

service:
  type: ClusterIP
  port: 8000

ingress:
  enabled: false

resources: {}
