services:
  gateway-api-1:
    build:
      dockerfile: ./Dockerfile
    command: --port 80
    environment:
      - SERVICE_NUMBER=1
    volumes:
      - .:/app
      - ./dummy_data:/data
      - ./keys:/keys
#  gateway-api-2:
#    build:
#      dockerfile: ./Dockerfile
#    command: --port 8080
#    environment:
#      - SERVICE_NUMBER=2
#    volumes:
#      - .:/app
#      - ./dummy_data:/data
#      - ./keys:/keys
#    depends_on:
#      - gateway-api-1
