name: Build and push Docker image

on:
  workflow_call:
    inputs:
      context:
        description: 'Path to the Docker image to build'
        default: ''
        type: string
jobs:
  container-image-build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        if: ${{ github.event_name == 'release' }}
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      # Extract metadata (tags, labels) for Docker
      # https://github.com/docker/metadata-action
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      - name: Build
        uses: docker/build-push-action@v6
        if: ${{ github.event_name != 'release' }}
        with:
          context: "{{defaultContext}}:${{ inputs.context }}"
          tags: "ghcr.io/${{ github.workspace }}/${{ inputs.context }}:test,${{ steps.meta.outputs.tags }}"
          push: false
      - name: Build and push
        uses: docker/build-push-action@v6
        if: ${{ github.event_name == 'release' }}
        with:
          context: "{{defaultContext}}:${{ inputs.context }}"
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          # tags: "ghcr.io/${{ github.workspace }}/${{ inputs.context }}:${{ github.ref_name }}"
          labels: ${{ steps.meta.outputs.labels }}