name: Build and push Docker image

on:
  workflow_call:
    inputs:
      context:
        description: "Path to the Docker image to build"
        default: ""
        type: string
      container-image-path:
        description: "Path of the docker image Tag"
        default: "ghcr.io/british-oceanographic-data-centre/amrit-repos/${{ inputs.context }}/app"
        type: string
jobs:
  container-image-build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        if: ${{ github.event_name == 'release' }}
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build
        uses: docker/build-push-action@v6
        if: ${{ github.event_name != 'release' }}
        with:
          context: "./${{ inputs.context }}"
          tags: "ghcr.io/british-oceanographic-data-centre/amrit-repos/${{ inputs.context }}/app:develop"
          push: false
      - name: Build and push
        uses: docker/build-push-action@v6
        if: ${{ github.event_name == 'release' }}
        with:
          context: "./${{ inputs.context }}"
          tags: "ghcr.io/british-oceanographic-data-centre/amrit-repos/${{ inputs.context }}/app:${{ github.ref_name }}"
          # tags: "ghcr.io/${{ github.repository }}:${{ github.ref_name }}" need to lowercase github.repository
          push: true
          labels: ${{ steps.meta.outputs.labels }}
