name: dagger run

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  dagger:
    name: dagger linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v3
      - name: Call Dagger Function
        uses: dagger/dagger-for-github@v6
        with:
          version: latest
          workdir: ./typescript-demo
          verb: call                  
          args: lint --scoure=./typescript-demo
          