name: dagger run

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  dagger:
    name: dagger linting
    runs-on: ubuntu-latest
    steps:
      - name: Call Dagger Function
        uses: dagger/dagger-for-github@v6
        with:
          version: "latest"
          verb: call
          module: ./dagger
          args: lint --scoure=./typescript-demo
          