name: Java Workflow

on:
  push:
    branches:
      - main
    paths:
      - 'java-demo/**'
  pull_request:
    paths:
      - 'java-demo/**'
jobs:
  java-linting:
    uses: British-Oceanographic-Data-Centre/amrit-repos/.github/workflows/java-lint-component.yml@feature/shared-ci
    with:
      context: java-demo
  java-testing:
    needs: java-linting
    uses: British-Oceanographic-Data-Centre/amrit-repos/.github/workflows/java-test-component.yml@feature/shared-ci
    with:
      context: java-demo
  container-image-build:
    needs: java-testing
    uses: British-Oceanographic-Data-Centre/amrit-repos/.github/workflows/container-image-component.yml@feature/shared-ci
    with:
      context: java-demo
  security-trivy-scan:
    needs: container-image-build
    uses: British-Oceanographic-Data-Centre/amrit-repos/.github/workflows/security-trivy-component.yml@feature/shared-ci
    with:
      context: java-demo