name: Java Workflow

on:
  push:
    branches:
      - main
    paths:
      - 'java-demo/**'
  pull_request:
    paths:
      - 'java-demo/**'
jobs:
  call-workflow-java-linting:
    uses: British-Oceanographic-Data-Centre/amrit-repos/.github/workflows/java-lint.yml@feature/shared-ci
    with:
      context: java-demo
