name: Java Build

on:
  push:
    branches:
      - main
  pull_request:
    paths:
    - 'java-demo/**'

jobs:
  build:
    env:
      shouldPushImage: ${{ github.ref == 'refs/head/main' }}
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:java-demo"
          push: ${{ env.shouldPushImage }}
          tags: ttl.sh/amrit-java-demo:24h