name: Java Lint

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - 'java-demo/**'
jobs:
  Spotlesslint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'
    - name: Run Spotless lint
      working-directory: ./java-demo
      run: ./mvnw spotless:check