name: Java Build

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - 'java-demo/**'
  release:
    types: [created]

jobs:
  build:
    env:
      rulePush: ${{ github.event_name != 'release' }}
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        if: ${{ env.rulePush }}
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build
        uses: docker/build-push-action@v6
        if: ${{ ! env.rulePush }}
        with:
          context: "{{defaultContext}}:java-demo"
          push: false
      - name: Build and push
        uses: docker/build-push-action@v6
        if: ${{ env.rulePush }}
        with:
          context: "{{defaultContext}}:java-demo"
          push: true
          tags: "ghcr.io/british-oceanographic-data-centre/amrit-repos/java/app:${{ github.ref_name }}"