name: Python Tox

on:
  push:
    branches:
      # Run on our main branch
      - main
  pull_request:  # Run for any pull requests

jobs:
  tox:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Run on Python versions that are stable and not EOL
        python-version: ["3.10", "3.11", "3.12", "3.13"]
    steps:
      - uses: actions/checkout@v4  # Checkout the current branch/merge state
      - name: Set up Python ${{ matrix.python-version }}  # Get Python ready to use
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies  # Get Tox and Poetry ready
        working-directory: ./example-python
        run: |
          python -m pip install --upgrade pip
          python -m pip install tox tox-gh-actions
          curl -sSL https://install.python-poetry.org | python -
          tox depends --recreate
      # Run Tox jobs
      - name: Build
        working-directory: ./example-python
        run: tox -e build
      - name: Lint
        working-directory: ./example-python
        run: tox -e lint
      - name: Type
        working-directory: ./example-python
        run: tox -e type
      - name: Test
        working-directory: ./example-python
        run: tox -e test
