# Workflow regarding python security scanning.
name: Python Security

on:
  push:
    branches:
      # Run on our main branch
      - main
    paths:
      - example-python/**
  pull_request:
    # Run for any pull requests
    paths:
      - example-python/**
jobs:
  # https://github.com/marketplace/actions/anchore-container-scan
  dependency-check:
    runs-on: ubuntu-latest
    permissions:
      # Required for uploading sarif file
      security-events: write
    steps:
      - uses: actions/checkout@v4  # Checkout the current branch/merge state
      - name: Grype Scan
        uses: anchore/scan-action@v3
        id: grype-scan
        with:
          path: example-python
      - name: Upload grype sarif file
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: ${{ steps.grype-scan.outputs.sarif }}
          category: grype-scan
      - name: Inspect grype SARIF report
        if: always()
        run: cat ${{ steps.grype-scan.outputs.sarif }}
      - name: Pip Audit
        uses: pypa/gh-action-pip-audit@v1.1.0
        with:
          inputs: example-python
  code-check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.13"]
    permissions:
      # Required for uploading sarif file
      security-events: write
    steps:
      - uses: actions/checkout@v4  # Checkout the current branch/merge state
      - name: Set up Python ${{ matrix.python-version }}  # Get Python ready to use
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies  # Install bandit
        working-directory: ./example-python
        run: |
          python -m pip install --upgrade pip
          python -m pip install bandit[toml,sarif]
      - name: Run Bandit
        working-directory: ./example-python
        # Run bandit and output to sarif file
        run: |
          bandit -r . -c pyproject.toml -f sarif -o bandit.sarif
      - name: Upload bandit sarif file
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: example-python/bandit.sarif
          category: bandit-python-analysis
      - name: Inspect bandit SARIF report
        if: always()
        run: cat bandit.sarif
