name: Typescript Build

on:
  push:
    branches:
      - main
  pull_request:
    paths:
    - 'typescript-demo/**'
  release:
    types: [created]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        if: ${{ github.event_name == 'release' }}
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build
        uses: docker/build-push-action@v6
        if: ${{ github.event_name != 'release' }}
        with:
          context: "{{defaultContext}}:example-python"
          push: false
      - name: Build and push
        uses: docker/build-push-action@v6
        if: ${{ github.event_name == 'release' }}
        with:
          context: "{{defaultContext}}:typescript-demo"
          push: true
          tags: "ghcr.io/british-oceanographic-data-centre/amrit-repos/typescript/app:${{ github.ref_name }}"
