name: Typescript Demo

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install modules
      working-directory: ./typescript-demo
      run: npm install
    - name: Run ESLint
      working-directory: ./typescript-demo
      run: npm run lint
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./typescript-demo
          push: false
          tags: amrit/ts-demo:latest
