name: Typescript Lint

on: [push]

jobs:
  eslint:
    runs-on: node20
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      working-directory: ./typescript-demo
      run: npm install
    - name: Run ESLint
      working-directory: ./typescript-demo
      run: npm run lint