name: TypeScript Workflow

on:
  push:
    branches:
      # Run on our main branch
      - main
    paths:
      - typescript-demo/**
  pull_request:
    # Run for any pull requests
    # paths:
    #   - typescript-demo/**
  # TODO : Do we have to keep that ?!
  # schedule:
  #   - cron: '*/15 * * * *'
  release:
    types: [created]

jobs:
  ts-linting:
    uses: British-Oceanographic-Data-Centre/amrit-repos/.github/workflows/component-ts-lint.yml@feature/shared-ci
    with:
      context: typescript-demo
  ts-security:
    uses: British-Oceanographic-Data-Centre/amrit-repos/.github/workflows/component-ts-security.yml@feature/shared-ci
    with:
      context: typescript-demo
  container-image-build:
    needs: [ts-linting, ts-security]
    uses: British-Oceanographic-Data-Centre/amrit-repos/.github/workflows/component-container-image.yml@feature/shared-ci
    with:
      context: typescript-demo
      image-path: ghcr.io/british-oceanographic-data-centre/amrit-repos/typescript/app
  container-image-security:
    needs: [container-image-build]
    uses: British-Oceanographic-Data-Centre/amrit-repos/.github/workflows/component-container-image-security.yml@feature/shared-ci
    with:
      context: typescript-demo
      image-path: ghcr.io/british-oceanographic-data-centre/amrit-repos/typescript/app
