name: TypeScript Workflow

on:
  push:
    branches:
      # Run on our main branch
      - main
    paths:
      - typescript-demo/**
  pull_request:
    # Run for any pull requests
    # paths:
    #   - typescript-demo/**
  release:
    types: [created]

jobs:
  java-linting:
    uses: British-Oceanographic-Data-Centre/amrit-repos/.github/workflows/component-ts-lint.yml@feature/shared-ci
    with:
      context: typescript-demo
  container-image-build:
    needs: java-testing
    uses: British-Oceanographic-Data-Centre/amrit-repos/.github/workflows/component-container-image.yml@feature/shared-ci
    with:
      context: typescript-demo
  security-trivy-scan:
    needs: container-image-build
    uses: British-Oceanographic-Data-Centre/amrit-repos/.github/workflows/component-security-trivy.yml@feature/shared-ci
    with:
      context: typescript-demo