name: Argo File Checker Python wrapper Workflow

on:
  push:
    branches:
      # Run on our main branch
      - main
    paths:
      - argofilechecker-python-wrapper/**
  pull_request:
    # Run for any pull requests
    paths:
      - argofilechecker-python-wrapper/**
  release:
    types: [created]

jobs:
  python-linting:
    uses: ./.github/workflows/component-python-lint.yml
    with:
      context: argofilechecker-python-wrapper
  python-security:
    uses: ./.github/workflows/component-python-security.yml
    with:
      context: argofilechecker-python-wrapper
  container-image-build:
    needs: [python-linting, python-security]
    uses: ./.github/workflows/component-container-image.yml
    with:
      context: argofilechecker-python-wrapper
      image-path: ghcr.io/british-oceanographic-data-centre/amrit-repos/argofilechecker-python/app
  publish-to-github-registry:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"  

      - name: Python Build
        run: |
          cd argofilechecker-python-wrapper
          python -m pip install --upgrade pip
          pip install poetry
          poetry build
      - name: Publish to GitHub Packages
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
        run: |

          cd argofilechecker-python-wrapper
          python -m pip install --upgrade pip
          pip install twine
          python -m twine upload \
          --repository-url https://pypi.pkg.github.com/amrit-eu \
          dist/*