name: Argo File Checker Python wrapper Workflow

on:
  push:
    branches:
      # Run on our main branch
      - main
    paths:
      - argofilechecker-python-wrapper/**
  pull_request:
    # Run for any pull requests
    paths:
      - argofilechecker-python-wrapper/**
  release:
    types: [created]

jobs:
  python-linting:
    uses: ./.github/workflows/component-python-lint.yml
    with:
      context: argofilechecker-python-wrapper
  python-security:
    uses: ./.github/workflows/component-python-security.yml
    with:
      context: argofilechecker-python-wrapper
  container-image-build:
    needs: [python-linting, python-security]
    uses: ./.github/workflows/component-container-image.yml
    with:
      context: argofilechecker-python-wrapper
      image-path: ghcr.io/british-oceanographic-data-centre/amrit-repos/argofilechecker-python/app
  container-image-security:
    needs: [container-image-build]
    uses: ./.github/workflows/component-container-image-security.yml
    with:
      context: argofilechecker-python-wrapper
      image-path: ghcr.io/british-oceanographic-data-centre/amrit-repos/argofilechecker-python/app
